import {useState} from 'react'
import {ArrowRight, Check, Phone, Sun} from 'lucide-react'

type Focus = 'home'|'routine'|'contact'
export function EverydayCanvas({onPlan,onCook}:{onPlan:()=>void;onCook:()=>void}) {
 const [focus,setFocus]=useState<Focus>('home')
 const [surface,setSurface]=useState('Desktop')
 const [context,setContext]=useState('Personal')
 const [skipped,setSkipped]=useState(false)
 const [evening,setEvening]=useState(false)
 const [choice,setChoice]=useState(false)
 const [calling,setCalling]=useState(false)
 const [linked,setLinked]=useState(false)
 const [independent,setIndependent]=useState(false)
 const [completed,setCompleted]=useState<string[]>([])
 const steps=['Get dressed','Have breakfast',...(!evening?['Pack lunch']:[]),'Bags by the door']
 return <section className="everyday"><div className="everyday-controls"><label>Surface <select value={surface} onChange={e=>{setSurface(e.target.value);setFocus('home');setCalling(false);if(e.target.value==='Wall')setContext('Family')}}>{['Desktop','Phone','Wall'].map(s=><option key={s}>{s}</option>)}</select></label><label>Context <select value={context} disabled={surface==='Wall'} onChange={e=>{setContext(e.target.value);setFocus('home');setCalling(false)}}>{['Personal','Work','Family'].map(s=><option key={s}>{s}</option>)}</select></label><span>{surface==='Wall'?'Shared household only':'Changing context does not share items'}</span></div>
 <div className="everyday-title"><Sun size={25}/><div><p className="eyebrow">MONDAY · OCTOBER 12 · SAMPLE DAY</p><h1>{focus==='routine'?'A calmer start.':focus==='contact'?'A familiar voice.':context==='Work'?'Room to focus.':context==='Family'?'Our day, together.':'A little room for today.'}</h1></div></div>
 {focus==='home'&&<div className="rest-grid"><section className="rest-panel"><p className="eyebrow">{surface==='Wall'?'NOW & NEXT':'YOUR NEXT STEPS'}</p>{context==='Work'?<><h2>Prepare for the next conversation.</h2><p>Review your questions before the afternoon meeting.</p></>:context==='Family'?<><h2>Get ready, together.</h2><p>Morning routine · four simple steps</p><button onClick={()=>setFocus('routine')}>Open our morning <ArrowRight size={16}/></button></>:<><h2>Book a training consultation.</h2><p>Connected to getting your training plan ready.</p><button onClick={()=>setFocus('contact')}>See the example contact <ArrowRight size={16}/></button></>}<button onClick={onPlan}>Return to planning <ArrowRight size={16}/></button></section><section className="rest-panel"><p className="eyebrow">{context==='Work'?'LATER':'THE SHAPE OF THE DAY'}</p><h2>{context==='Work'?'A clear stopping point.':'Space between the commitments.'}</h2><p>{context==='Work'?'2:00 · Project conversation':'3:15 · School pickup'}</p><p>{context==='Work'?'4:30 · Wrap up and plan tomorrow':'6:30 · Dinner together'}</p>{context!=='Work'&&<button onClick={onCook}>Tomato pasta & salad <ArrowRight size={16}/></button>}</section>{context==='Personal'&&!linked&&!independent&&<section className="rest-panel suggestion"><p className="eyebrow">A POSSIBLE CONNECTION · NOT SAVED</p><h2>“Book a training consultation”</h2><p>This recent sample capture could support “Get a training plan ready to follow.”</p><button onClick={()=>setLinked(true)}>Connect sample item <Check size={16}/></button><button onClick={()=>setIndependent(true)}>Keep independent</button></section>}{context==='Personal'&&(linked||independent)&&<p role="status">{linked?'Sample connection accepted.':'Sample item kept independent.'} Nothing changed in your account.</p>}</div>}
 {focus==='routine'&&<section className="rest-panel routine-panel"><p className="eyebrow">FAMILY · SCHOOL MORNINGS</p><p>A repeating pattern. Today’s changes need not change tomorrow.</p>{steps.map(step=><div className="routine-row" key={step}><label><input type="checkbox" checked={completed.includes(step)} onChange={()=>setCompleted(old=>old.includes(step)?old.filter(x=>x!==step):[...old,step])}/><span>{step}{step==='Pack lunch'&&skipped?' · skipped today':''}</span></label>{step==='Pack lunch'&&<button onClick={()=>setChoice(true)}>Adjust</button>}</div>)}{choice&&<div className="routine-choice"><h3>Change packing lunch</h3><button onClick={()=>{setSkipped(true);setChoice(false)}}>Skip only today</button><button onClick={()=>{setEvening(true);setChoice(false)}}>Move to evenings from now on</button><button onClick={()=>setChoice(false)}>Cancel</button></div>}{evening&&<p role="status">Pack lunch is now in the sample evening routine. Future mornings omit it.</p>}{skipped&&!evening&&<p role="status">Skipped today. Packing lunch stays in the standing morning routine.</p>}<button onClick={()=>setFocus('home')}>Back to our day</button></section>}
 {focus==='contact'&&<section className="rest-panel contact-panel"><p className="eyebrow">FICTIONAL CONTACT · CALLING REHEARSAL</p><div className="contact-avatar">AL</div><h2>Alex Lee</h2><p>Training consultation · example contact attached to your task</p><p>{calling?'Call interface preview — no connection is being made.':'Opening this card does not place a call.'}</p><button onClick={()=>setCalling(v=>!v)}><Phone size={17}/>{calling?'End simulation':'Simulate call'}</button><button onClick={()=>{setCalling(false);setFocus('home')}}>Back to my day</button><small>Production calling will use kidsPhone and its contact permissions. No telephony is connected here.</small></section>}
 <div className="rest-footer"><span>This view stays put until you choose a different focus.</span><button onClick={()=>{setContext('Family');setFocus('routine')}}>Show our morning routine</button></div></section>
}
