import {useEffect,useLayoutEffect,useReducer,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {ArrowUp,ArrowRight,ArrowLeft,Check,Plus,X,Volume2,VolumeX,Leaf,Heart,Compass,Sun,Utensils,Clock,BookOpen,Pause,MoveUpRight} from 'lucide-react'
import {initialState,reducer,sceneLibrary,sequence,type Thread,type PlanScene} from './model'
import './style.css'
const symbols={health:Leaf,family:Heart,work:Compass,home:Sun}
const fieldNames={year:'Yearly intention',season:'Seasonal milestone',month:'Monthly plan',week:'Weekly action'}
function App(){
 const [state,dispatch]=useReducer(reducer,initialState)
 const [input,setInput]=useState(''),[audio,setAudio]=useState(false),[speaking,setSpeaking]=useState(false),[audioNote,setAudioNote]=useState(''),[editing,setEditing]=useState<{id:string;field:keyof typeof fieldNames}|null>(null),[editValue,setEditValue]=useState(''),[adding,setAdding]=useState(false),[extras,setExtras]=useState<Record<string,string>>({}),[paused,setPaused]=useState(false)
 const [compact,setCompact]=useState(false)
 const extra=extras[state.scene]||''
 const setExtra=(value:string)=>setExtras(old=>({...old,[state.scene]:value}))
 const editRef=useRef<HTMLDialogElement>(null)
 const canvasRef=useRef<HTMLElement>(null)
 const scrollMemory=useRef(new Map<string,number>())
 const cards=useRef(new Map<string,HTMLElement>())
 const positions=useRef(new Map<string,DOMRect>())
 const scene=sceneLibrary[state.scene]
 const plan=sequence.includes(state.scene as PlanScene)
 const stage=sequence.indexOf(state.scene as PlanScene)
 const currentField=state.scene==='year'?'year':state.scene==='season'?'season':state.scene==='month'?'month':'week'
 const say=(text:string)=>{if(canvasRef.current)scrollMemory.current.set(state.scene,canvasRef.current.scrollTop);if('speechSynthesis'in window)window.speechSynthesis.cancel();setSpeaking(false);setPaused(false);dispatch({type:'say',text});setInput('')}
 useLayoutEffect(()=>{if(canvasRef.current)canvasRef.current.scrollTop=scrollMemory.current.get(state.scene)||0;const next=new Map<string,DOMRect>();cards.current.forEach((el,id)=>{const rect=el.getBoundingClientRect();next.set(id,rect);const previous=positions.current.get(id);if(previous&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const dx=previous.left-rect.left,dy=previous.top-rect.top;if(dx||dy)el.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:560,easing:'cubic-bezier(.2,.7,.2,1)'})}});positions.current=next},[state.scene,compact])
 useEffect(()=>{if(!audio||paused||!('speechSynthesis'in window))return;const voice=window.speechSynthesis.getVoices().find(v=>v.localService&&v.lang.startsWith('en'));if(!voice)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(state.reply);utterance.voice=voice;utterance.rate=.94;utterance.onstart=()=>setSpeaking(true);utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>{setSpeaking(false);setAudioNote('Audio stopped. You can keep going by text.')};window.speechSynthesis.speak(utterance);return()=>window.speechSynthesis.cancel()},[audio,paused,state.reply])
 useEffect(()=>{if(editing)editRef.current?.showModal()},[editing])
 const beginEdit=(t:Thread,field:keyof typeof fieldNames)=>{setEditing({id:t.id,field});setEditValue(t[field])}
 const cleanSaved=state.saved&&JSON.stringify(state.saved)===JSON.stringify(state.draft)
 return <div className={`living ${compact?'compact':''} ${speaking?'speaking':''}`}><div className="rehearsal"><span>INTERACTION STUDY · SCRIPTED CONVERSATION · FICTIONAL DATA</span><button aria-pressed={compact} onClick={()=>setCompact(v=>!v)}>{compact?'Expand canvas':'Try a narrow canvas'}</button></div><div className="shell"><header className="identity"><a href="./index.html" aria-label="Restart sample rehearsal" className="wordmark">✳ <span>SYMPHONY</span></a><span className="context">{state.scene==='dinner'||state.scene==='cooking'?'Shared household example':'Your planning example'}</span><button className="audio-toggle" aria-pressed={audio} onClick={()=>{if(audio){setAudio(false);window.speechSynthesis?.cancel();setSpeaking(false)}else if(!('speechSynthesis'in window)||!window.speechSynthesis.getVoices().some(v=>v.localService&&v.lang.startsWith('en'))){setAudioNote('No local English voice is available here. Continue by text, or try again once voices have loaded.')}else{setAudioNote('');setAudio(true)}}}>{audio?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{audio?'Read replies on':'Hear replies'}</span></button></header>
 <main ref={canvasRef} className={`canvas scene-${state.scene}`} data-component={scene.kind}>
 <div className="scene-heading" key={state.scene}><div><p className="eyebrow">{scene.eyebrow}</p><h1>{scene.title}</h1></div>{plan&&<div className="draft-badge"><span/>{cleanSaved?'Sample saved':'Draft · yours to shape'}</div>}</div>
 {state.scene==='welcome'&&<div className="welcome-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="seed seed-a"><Leaf/></div><div className="seed seed-b"><Heart/></div><div className="seed seed-c"><Compass/></div><div className="seed seed-d"><Sun/></div><div className="welcome-center">A thought.<br/><em>A direction.</em><br/>A next step.</div></div>}
 {plan&&<><div className="plan-field" data-stage={state.scene}>{state.draft.threads.map((thread,index)=>{const Icon=symbols[thread.id as keyof typeof symbols]||Leaf;return <article className={`thread ${thread.color}`} key={thread.id} ref={el=>{if(el)cards.current.set(thread.id,el);else cards.current.delete(thread.id)}}><div className="thread-origin"><div className="thread-meta"><span className="area-icon"><Icon size={20}/></span><small>{thread.area}</small><span className="thread-number">0{index+1}</span></div><button className="intention" onClick={()=>beginEdit(thread,'year')}>{thread.year}</button>{state.scene==='year'&&<div className="thread-landscape" aria-hidden="true"><span/><i/></div>}</div>{stage>=1&&stage<=3&&<div className="thread-development" key={state.scene}><small>{fieldNames[currentField]}</small>{stage>=2&&<p className="previous">{thread[state.scene==='month'?'season':'month']}</p>}<button className="developed-title" onClick={()=>beginEdit(thread,currentField)}>{thread[currentField]||'Give this a little shape…'}<MoveUpRight size={13}/></button><span className="connection-caption">{state.scene==='week'?'A possible action, linked to October':'Connected to the same intention'}</span></div>}{state.scene==='summary'&&<ol className="whole-thread"><li><span>Fall</span>{thread.season}</li><li><span>October</span>{thread.month}</li><li><span>This week</span>{thread.week}</li><li className={state.draft.today.includes(thread.id)?'chosen':''}><span>Today</span>{state.draft.today.includes(thread.id)?'Chosen for today':'Stays in this week’s plan'}</li></ol>}</article>})}</div>
 {stage>=0&&stage<=3&&<div className="freeform"><button onClick={()=>setAdding(v=>!v)}><Plus size={16}/>{state.scene==='year'?'Add another intention':'Add something independently'}</button>{state.draft.other.filter(i=>i.period===state.scene).map(i=><span key={i.id}>{i.title}</span>)}{adding&&<form onSubmit={e=>{e.preventDefault();if(extra.trim()){dispatch({type:'add',title:extra.trim(),period:state.scene as PlanScene});setExtra('');setAdding(false)}}}><input aria-label="Independent draft entry" value={extra} onChange={e=>setExtra(e.target.value)} placeholder="Your words, no bigger connection needed…" maxLength={200}/><button disabled={!extra.trim()}>Add to draft <ArrowRight size={15}/></button></form>}</div>}
 {state.scene==='today'&&<section className="day-composition"><div className="day-actions"><p className="eyebrow">CHOOSE WHAT FITS</p>{state.draft.threads.filter(t=>t.week.trim()).map(t=><label key={t.id} className={state.draft.today.includes(t.id)?'selected':''}><input type="checkbox" checked={state.draft.today.includes(t.id)} onChange={()=>dispatch({type:'selectToday',id:t.id})}/><div>{t.week}<small>{t.month}</small></div><span className="action-dot"/></label>)}<p className="capacity">{state.draft.today.length} chosen. The rest stay available for this week.</p></div><div className="day-space"><p className="eyebrow">MONDAY · OCTOBER 12</p><div className="time-slot"><time>Morning</time><p>Room for a next step</p><span className="open-time"/></div><div className="time-slot"><time>3:15</time><p>School pickup</p></div><div className="time-slot"><time>6:30</time><p>Dinner together</p><button onClick={()=>say('What’s for dinner?')}>See tonight’s meal <ArrowRight size={14}/></button></div><small>Illustrative calendar · not your live availability</small></div></section>}
 {state.scene==='summary'&&<div className="save-plan"><div><strong>{cleanSaved?'Saved for this rehearsal.':'Ready to keep this plan?'}</strong><p>Saving is separate from exploring. This only saves a copy in the prototype’s memory.</p></div><button disabled={!!cleanSaved} onClick={()=>dispatch({type:'save'})}><Check size={18}/>{cleanSaved?'Sample saved':'Save sample plan'}</button></div>}
 <div className="path-memory"><span className="path-line"/>{['Year','Season','Month','Week','Today'].map((name,i)=><span key={name} className={i<=stage?'visited':''}>{i===stage?<i/>:null}{name}</span>)}<small>{state.scene==='summary'?'All periods, one plan':`${Math.min(stage+1,5)} of 5 · all intentions together`}</small></div></>}
 {(state.scene==='dinner'||state.scene==='cooking')&&<><div className="return-thread"><span className="tiny-thread"/><span>Your {state.returnTo==='summary'?'planning':state.returnTo} conversation is waiting.</span><button onClick={()=>say('Back to my planning conversation')}>Return <ArrowLeft size={14}/></button></div>{state.scene==='dinner'?<div className="meal-focus"><div className="meal-illustration" aria-hidden="true"><div className="napkin"/><div className="plate"><div className="pasta"/><i/><b/><em/></div><span className="fork">∥</span><div className="herb"><Leaf/><Leaf/><Leaf/></div></div><div className="meal-copy"><div className="meal-meta"><Utensils size={16}/> TONIGHT · SERVES FOUR</div><h2>Tomato pasta<br/>& a crisp salad.</h2><p>A simple dinner, with a little room to breathe.</p><span className="meal-time"><Clock size={16}/> About 30 minutes</span><button className="primary" onClick={()=>say('Show me the recipe')}>Let’s cook <ArrowRight size={17}/></button></div></div>:<div className="cooking-focus"><section className="ingredients"><h2>Gather what you need.</h2><small>{state.checkedIngredients.length} of 5 ready</small>{['Pasta','Cherry tomatoes','Olive oil','Fresh basil','Salad leaves'].map(name=><label key={name}><input type="checkbox" checked={state.checkedIngredients.includes(name)} onChange={()=>dispatch({type:'ingredient',name})}/><span>{name}</span></label>)}</section><section className="steps"><h2>On the stove.</h2>{['Cook the pasta according to the packet.','Warm the tomatoes in olive oil until they soften.','Toss with pasta and basil. Serve with dressed leaves.'].map((text,i)=><div className="recipe-step" key={text}><span>0{i+1}</span><p>{text}</p></div>)}<p className="recipe-note">Example recipe · ingredient checks stay in place while you talk.</p></section></div>}</>}
 </main>
 <section className={`conversation-dock ${paused?'paused':''}`} aria-label="Conversation"><div className="spoken-line"><div className="presence" aria-hidden="true"><span/><span/><span/><span/></div><div className="voice-copy">{state.heard&&<p className="last-utterance">You · {state.heard}</p>}<p className="reply" aria-live="polite">{paused?'Take your time. Your canvas is still here.':state.reply}</p></div><button className="pause" aria-label={paused?'Resume conversation':'Pause conversation'} onClick={()=>{setPaused(v=>!v);window.speechSynthesis?.cancel();setSpeaking(false)}}>{paused?<ArrowRight size={19}/>:<Pause size={17}/>}</button></div>{!paused&&<><div className="phrase-options" aria-label="Suggested replies">{scene.chips.map(text=><button key={text} onClick={()=>say(text)}>{text}<ArrowUp size={13}/></button>)}</div><form className="conversation-input" onSubmit={e=>{e.preventDefault();if(input.trim())say(input.trim())}}><span className="prompt-mark">✳</span><input aria-label="Say something to Symphony" value={input} onChange={e=>setInput(e.target.value)} placeholder="Try a phrase above, or type one…" maxLength={240}/><button disabled={!input.trim()} aria-label="Send your thought"><ArrowUp size={18}/></button></form></>}<div className="conversation-foot"><span>{speaking?'Speaking · send a thought to interrupt':'Text rehearsal · microphone not connected'}</span><span>{audioNote||'Sample changes reset on reload'}</span></div></section>
 </div><footer className="study-explainer"><span><BookOpen size={15}/> Conversation selects from a designed visual library. Exploring changes the view; saving changes the sample plan.</span><a href="../symphony-design-study/index.html">Earlier surface study <ArrowRight size={13}/></a></footer>
 {editing&&<dialog ref={editRef} className="edit-dialog" aria-label="Shape this part of your plan" onClose={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();if(editValue.trim()){dispatch({type:'edit',...editing,value:editValue.trim()});editRef.current?.close()}}}><div className="edit-heading"><span>{fieldNames[editing.field]}</span><button type="button" aria-label="Cancel edit" onClick={()=>editRef.current?.close()}><X size={19}/></button></div><h2>Make it yours.</h2><textarea aria-label="Plan wording" value={editValue} onChange={e=>setEditValue(e.target.value)} maxLength={180}/><p>Updates the draft, keeping its connections. Nothing is saved to your account.</p><button className="primary" disabled={!editValue.trim()}><Check size={16}/> Update draft</button></form></dialog>}
 </div>
}
const root=createRoot(document.getElementById('root')!)
root.render(<App/> )
if(import.meta.hot)import.meta.hot.dispose(()=>root.unmount())
