import {useState} from 'react'
import {createRoot} from 'react-dom/client'
import {initial,descendants,add,type Node} from '../plan-shapes/model'
import './style.css'
const names=['Year','Season','Month','Week'], labels=['Intentions','Goals','Milestones','Actions'], periods=['2026','Fall','October','Oct 11–17']
function App(){
 const [nodes,setNodes]=useState(initial),[root,setRoot]=useState('family'),[selected,setSelected]=useState('weekends'),[all,setAll]=useState(false),[horizon,setHorizon]=useState(1),[edit,setEdit]=useState(false),[draft,setDraft]=useState(''),[adding,setAdding]=useState(false)
 const focus=nodes.find(n=>n.id===selected)!, related=new Set([root,...descendants(nodes,root).map(n=>n.id)])
 const linked=new Set([selected,...descendants(nodes,selected).map(n=>n.id)]);let ancestor=focus;while(ancestor?.parent){linked.add(ancestor.parent);ancestor=nodes.find(n=>n.id===ancestor.parent)!}
 function choose(n:Node){setSelected(n.id);setEdit(false);setAdding(false);if(n.level===0){setRoot(n.id);setAll(false)}}
 function save(){if(!draft.trim())return;if(adding){const node={id:crypto.randomUUID(),parent:focus.id,level:focus.level+1,text:draft.trim(),color:focus.color};setNodes(old=>add(old,node))}else setNodes(old=>old.map(n=>n.id===selected?{...n,text:draft.trim()}:n));setEdit(false);setAdding(false)}
 return <div className="study"><div className="sample">DESIGN STUDY · SAMPLE DATA · RESETS ON RELOAD</div><header><span>✳ S Y M P H O N Y</span><span>Your plans, connected</span><a href="../plan-shapes/index.html">Previous study ↗</a></header><div className="intro"><div><small>THE BIG PICTURE</small><h1>Room for what matters.</h1><p>Each horizon brings your intentions closer to everyday life.</p></div><div className="modes"><button aria-pressed={!all} onClick={()=>setAll(false)}>Explore an intention</button><button aria-pressed={all} onClick={()=>setAll(true)}>Plan a whole horizon</button></div></div>
 <div className="orientation">{all?<><strong>Planning across all intentions</strong><span>Choose a column heading to focus on that horizon.</span></>:<><strong>{nodes.find(n=>n.id===root)?.text}</strong><span>All its branches are shown. Select an item to trace its connections.</span></>}</div>
 <main className="zones">{names.map((name,level)=>{const rows=nodes.filter(n=>n.level===level&&(level===0||all||related.has(n.id)));return <section className={`zone z${level} ${all&&horizon===level?'active-horizon':''}`} key={name}><button className="zone-heading" onClick={()=>{setAll(true);setHorizon(level)}} aria-pressed={all&&horizon===level}><span>{name}<i aria-hidden="true">→</i></span><h2>{labels[level]}</h2><small>{periods[level]} · {rows.length}</small></button><div className="items">{rows.map(n=><button key={n.id} className={`item ${selected===n.id?'selected':''} ${linked.has(n.id)?'linked':''}`} aria-pressed={selected===n.id} onClick={()=>choose(n)}>{level>0&&<small>{nodes.find(p=>p.id===n.parent)?.text||'Independent'}</small>}<span>{n.text}</span>{level===0&&<em>{nodes.filter(p=>p.parent===n.id).length} seasonal goals</em>}</button>)}{!rows.length&&<p className="empty">Space for what comes next.</p>}</div></section>})}</main>
 <aside className="selection" aria-label="Selected item"><div><small>{labels[focus.level]} · SELECTED</small><h3>{focus.text}</h3><p>{focus.parent?`Connected to ${nodes.find(n=>n.id===focus.parent)?.text}`:'An intention for your year'}</p></div><div className="actions"><button onClick={()=>{setDraft(focus.text);setEdit(true);setAdding(false)}}>Edit wording</button>{focus.level<3&&<button onClick={()=>{setDraft('');setAdding(true);setEdit(true)}}>+ Add {labels[focus.level+1].slice(0,-1).toLowerCase()}</button>}</div>{edit&&<form onSubmit={e=>{e.preventDefault();save()}}><label>{adding?'New connected item':'Wording'}<input autoFocus value={draft} onChange={e=>setDraft(e.target.value)}/></label><button disabled={!draft.trim()}>Keep in sample</button><button type="button" onClick={()=>{setEdit(false);setAdding(false)}}>Cancel</button></form>}</aside><footer>Color identifies the horizon. A dark outline marks your selection; the softer outlines trace its connected path. No live account changes.</footer></div>
}
createRoot(document.getElementById('root')!).render(<App/> )
