import { useState, useEffect, useRef } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
type Surface = 'desktop'|'phone'|'wall'
const suggestions = [
 {id:'kit',title:'Put the swim bag by the door',why:'Sam has swimming at 4:00 pm.',person:'Sam'},
 {id:'lunch',title:'Pack lunches this evening',why:'School starts at 8:30 am.',person:'Anyone'},
 {id:'ride',title:'Confirm who is doing pickup',why:'School pickup and swimming are close together.',person:'Anyone'},
]
function Detail({text,close}:{text:string;close:()=>void}){
 const ref=useRef<HTMLDialogElement>(null)
 useEffect(()=>{ref.current?.showModal()},[])
 return <dialog ref={ref} className="detail" aria-label="Sample item details" onClose={close}><h2>A closer look</h2><p>{text}</p><button className="primary" onClick={()=>ref.current?.close()}>Back to the canvas</button></dialog>
}
function App(){
 const [surface,setSurface]=useState<Surface>('desktop')
 const [tomorrow,setTomorrow]=useState(false)
 const [guide,setGuide]=useState(false)
 const [selected,setSelected]=useState<string[]>(['kit','lunch','ride'])
 const [saved,setSaved]=useState<string[]>([])
 const [done,setDone]=useState<string[]>([])
 const [message,setMessage]=useState('')
 const [input,setInput]=useState('')
 const [custom,setCustom]=useState<string[]>([])
 const [phoneTab,setPhoneTab]=useState<'plan'|'conversation'>('plan')
 const [details,setDetails]=useState<string|null>(null)
 const begin=()=>{setTomorrow(true);setGuide(true);setPhoneTab('conversation');setMessage('')}
 const home=()=>{setTomorrow(false);setGuide(false);setPhoneTab('plan');setMessage('Back to Today. Your sample preparation list is still here.')}
 const add=()=>{const additions=selected.filter(id=>!saved.includes(id));setSaved([...saved,...additions]);setMessage(additions.length?`Added ${additions.length} ${additions.length===1?'item':'items'} to the sample preparation list. Nothing was added to your real account.`:'These items are already in the sample preparation list.');setPhoneTab('plan')}
 const send=()=>{if(!input.trim())return;setMessage('This rehearsal supports the prompts below. It does not interpret free-form requests yet.');}
 return <><div className="study"><span>DESIGN REHEARSAL · FICTIONAL HOUSEHOLD · NO ACCOUNT CONNECTION</span><div role="group" aria-label="Preview layout">{(['desktop','phone','wall'] as const).map(s=><button key={s} aria-pressed={surface===s} onClick={()=>{setSurface(s);setDetails(null)}}>{s==='desktop'?'Web / desktop':s[0].toUpperCase()+s.slice(1)}</button>)}</div></div>
 <div className={`app ${surface}`}><header><a href="../conversation-lab/index.html" className="brand">✳ <span>SYMPHONY</span></a><nav aria-label="Planning"><button onClick={home} aria-current={!tomorrow?'page':undefined}>Today</button><button onClick={()=>{setTomorrow(true);setGuide(false);setPhoneTab('plan')}} aria-current={tomorrow?'page':undefined}>Tomorrow</button></nav><span className="scope">{surface==='wall'?'◉ Household only':'◉ Family'}</span></header>
 <div className="masthead"><div><p className="eyebrow">{tomorrow?'A LITTLE PREPARATION, A LIGHTER MORNING':'AT HOME, TOGETHER'}</p><h1>{tomorrow?'Tomorrow, a little clearer.':'A little room for today.'}</h1><p className="date">{tomorrow?'Tuesday, October 13':'Monday, October 12'} <span>· illustrative day</span></p></div><button className="guide-toggle" onClick={()=>{if(!guide)begin();else{setGuide(false);setPhoneTab('plan')}}}>{guide?'Close conversation':'✳ Get ready for tomorrow'}</button></div>
 {tomorrow&&<div className="focus-strip"><span>Looking ahead to tomorrow · your usual cards, brought into focus</span><button onClick={home}>Back to Today ↗</button></div>}
 <div className="status" role="status" aria-live="polite">{message}</div>
 <div className="phone-tabs" role="group" aria-label="Workspace"><button aria-pressed={phoneTab==='plan'} onClick={()=>setPhoneTab('plan')}>My canvas</button><button aria-pressed={phoneTab==='conversation'} onClick={begin}>Conversation</button></div>
 <main className={`workspace ${guide?'with-guide':''} showing-${phoneTab}`}><section className="canvas" aria-label="Daily canvas"><div className="cards"><article className={`card schedule ${tomorrow?'in-focus':''}`}><div className="card-top"><span className="icon">◷</span><h2>The day</h2><small>{tomorrow?'TOMORROW':'TODAY'}</small></div><p className="reason">{tomorrow?'A school day, with swimming after pickup.':'The household’s shared schedule.'}</p>{(tomorrow?[['8:30','School','Sam & Riley'],['3:15','School pickup','Jordan'],['4:00','Swimming','Sam']]:[['3:15','School pickup','Alex'],['5:30','A walk together','Everyone'],['6:30','Dinner','Everyone']]).map(([time,title,person])=><button className="event" key={title} onClick={()=>setDetails(`${title} · ${time} · ${person}. Fictional shared calendar entry.`)}><time>{time}</time><span><strong>{title}</strong><small>{person}</small></span><span className="arrow">↗</span></button>)}</article>
 <article className="card dinner"><div className="card-top"><span className="icon">◒</span><h2>At the table</h2><small>6:30 PM</small></div><div className="meal-art" aria-hidden="true"><span>◯</span><i>✳</i></div><h3>{tomorrow?'Roast vegetables & couscous':'Tomato pasta & salad'}</h3><p className="reason">A shared dinner plan. About 30 minutes.</p><button className="text-link" onClick={()=>setDetails('Sample shopping list: carrots, peppers, couscous, chickpeas. This list is illustrative; nothing is ordered or saved.')}>See what we need ↗</button></article>
 <article className={`card preparation ${guide?'in-focus':''}`}><div className="card-top"><span className="icon">☷</span><h2>A little preparation</h2><small>{saved.length+custom.length} ITEMS</small></div><p className="reason">{saved.length?'Chosen for the sample plan. Check things off as you do them.':'A place for the small things that make tomorrow easier.'}</p>{!saved.length&&!custom.length&&<div className="empty"><span>✧</span><p>Nothing chosen yet.</p><button onClick={begin}>Think it through together →</button></div>}{saved.map(id=>{const item=suggestions.find(s=>s.id===id)!;return <label className={`task ${done.includes(id)?'done':''}`} key={id}><input type="checkbox" checked={done.includes(id)} onChange={()=>setDone(done.includes(id)?done.filter(x=>x!==id):[...done,id])}/><span>{item.title}<small>{item.person} · sample plan</small></span></label>})}{custom.map((t,i)=><label key={i} className="task"><input type="checkbox"/><span>{t}<small>Added by you · sample plan</small></span></label>)}<form className="quick-add" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const value=new FormData(form).get('task')?.toString().trim();if(value){setCustom([...custom,value]);form.reset();setMessage('Added to the sample preparation list.')}}}><input name="task" aria-label="Add a preparation task" placeholder="Add something yourself…" maxLength={160}/><button aria-label="Add preparation task">+</button></form>{saved.length>0&&<button className="undo" onClick={()=>{setSaved([]);setDone([]);setMessage('Suggested items removed from the sample plan. Your own additions remain.')}}>Undo suggested additions</button>}</article>
 <article className="card note"><div className="card-top"><span className="icon">☀</span><h2>Before you head out</h2></div><p className="weather">A cool start.<br/><em>Bring a light layer.</em></p><p className="reason">Example forecast · 54° morning / 68° afternoon</p><p className="shared-note">{surface==='wall'?'This wall shows shared household information. Private work and personal items stay off the display.':'Shared household context. Private work and personal items are not part of this rehearsal.'}</p></article></div></section>
 {guide&&<aside className="conversation" aria-label="Conversation"><div className="conversation-head"><span>✳</span><div><h2>Think it through</h2><small>WITH SYMPHONY · SCRIPTED REHEARSAL</small></div></div><div className="you">Help us get ready for tomorrow.</div><p className="assistant">Tomorrow has school and swimming. Let’s make the morning easier without planning every minute.</p><p className="assistant">Here are three things you might prepare. Choose what helps.</p><div className="suggestions">{suggestions.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>setSelected(selected.includes(item.id)?selected.filter(x=>x!==item.id):[...selected,item.id])}/><span><strong>{item.title}</strong><small>{item.why}</small></span></label>)}</div><div className="suggestion-status">{saved.length?'Previously added items won’t be duplicated.':'Suggestions only · nothing added yet'}</div><button className="primary" disabled={!selected.some(x=>!saved.includes(x))} onClick={add}>{selected.length&&!selected.some(x=>!saved.includes(x))?'Already in sample plan':`Add ${selected.filter(x=>!saved.includes(x)).length} to sample plan →`}</button><button className="quiet" onClick={()=>{setPhoneTab('plan');setMessage('Your preparation card is ready for direct entry.')}}>I’ll add my own</button><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><input aria-label="Message Symphony" value={input} onChange={e=>setInput(e.target.value)} placeholder="Type a thought…"/><button aria-label="Send message">↑</button></form><p className="rehearsal-note">For now, this conversation is scripted. Live AI and voice are not connected.</p></aside>}
 </main><footer><span>Same home. A different focus.</span><span>Sample changes last until you reload.</span></footer>
 {details&&<Detail text={details} close={()=>setDetails(null)}/>}
 </div></>
}
createRoot(document.getElementById('root')!).render(<App />)
