import {useState} from 'react'
import {Clock,Sun,Utensils,ArrowRight} from 'lucide-react'
import {dates} from './model'
const routineSteps=['Pack school bags','Check tomorrow’s calendar','Set out clothes']
export function DayContext({day}:{day:string}){
 const [done,setDone]=useState<Record<string,string[]>>({}),[recipe,setRecipe]=useState(false)
 const checked=done[day]||[]
 return <div className="day-context"><section className="agenda"><div className="context-heading"><Clock size={18}/><h2>On the calendar</h2><small>Sample appointments</small></div>{day===dates[0]?<ol><li><time>3:15 <small>PM</small></time><div>School pickup<span>Family · 30 minutes</span></div></li><li><time>6:30 <small>PM</small></time><div>Dinner together<span>Family · at home</span></div></li></ol>:<p className="hint">No sample appointments on this day. Your tasks above are still planned for the day, without a fixed time.</p>}</section><div className="household-context"><section className="routine"><div className="context-heading"><Sun size={18}/><h2>A calmer tomorrow</h2></div><p className="context-caption">Evening routine · Family · {checked.length} of {routineSteps.length}</p><progress max={routineSteps.length} value={checked.length} aria-label="Evening routine progress"/>{routineSteps.map(step=><label key={step}><input type="checkbox" checked={checked.includes(step)} onChange={()=>setDone(old=>({...old,[day]:checked.includes(step)?checked.filter(s=>s!==step):[...checked,step]}))}/><span>{step}</span></label>)}<small>Checks apply to this day only.</small></section><section className="dinner"><div className="context-heading"><Utensils size={18}/><h2>At the table</h2></div><p className="context-caption">Family · sample meal</p><h3>{day===dates[0]?'Tomato pasta & salad':'Room to decide.'}</h3>{day===dates[0]?<><p>30 minutes · serves four</p><button aria-expanded={recipe} onClick={()=>setRecipe(v=>!v)}>{recipe?'Close recipe':'Open recipe'} <ArrowRight size={14}/></button>{recipe&&<div className="inline-recipe"><h4>Gather</h4><p>Pasta, cherry tomatoes, olive oil, basil, salad leaves.</p><h4>Cook</h4><ol><li>Cook pasta according to the packet.</li><li>Soften tomatoes in olive oil.</li><li>Toss with pasta and basil. Serve with salad.</li></ol><small>Illustrative recipe; no live meal plan connected.</small></div>}</>:<p>No meal selected in this sample.</p>}</section></div></div>
}
