// src/components/planning/guided/sessions.ts
//
// The five guided rituals, as pure data. Narration strings here are BOTH the
// on-screen instruction and the spoken voice track (generated by
// scripts/generate-narration.ts). Keep this file free of component imports.

import type { GuidedSessionConfig } from './types'
import type { PlanningHorizon } from '@/hooks/usePlanningSession'

export const SESSIONS: Record<PlanningHorizon, GuidedSessionConfig> = {
  annual: {
    horizon: 'annual',
    title: 'Plan the year',
    estMinutes: [45, 60],
    chain: { horizon: 'seasonal', label: 'Plan the season now' },
    steps: [
      {
        id: 'welcome', type: 'narration', title: 'A year, on purpose',
        narration: 'This is the annual session. One hour, once a year: look back honestly, decide where the next twelve months should end up, and write it down where the rest of the system can see it. Every step is skippable and you can come back anytime. Find somewhere quiet, and when you are ready, continue.',
      },
      {
        id: 'looking-back', type: 'reflect', title: 'Look back',
        narration: 'Start with the year behind you. What actually moved, and what are you proud of? And which habits or commitments cost more than they returned? Read the failures like data, not verdicts — what happened, not whose fault. Write freely; this is for you.',
        props: { notesKey: 'review', placeholder: "What moved, what stalled, and what it cost…" },
      },
      {
        id: 'one-year-out', type: 'reflect', title: 'One year from now',
        narration: 'Now jump forward twelve months and assume it went well. Write it in the past tense: shipped, fixed, finally did. Past tense forces specifics; future tense lets you stay vague. Name what happened, and the two or three moves that made it happen.',
        props: { notesKey: 'lookingBack', placeholder: "It’s July 2027. What actually happened:" },
      },
      {
        id: 'goal-review', type: 'review', title: 'Your goals, so far',
        narration: 'Here are the goals you set before. If one happened, mark it achieved and take the second of credit. If it still matters, carry it into the new year. If it no longer fits, let it go — dropping a goal on purpose is editing, not failing.',
        props: { source: 'goals' },
      },
      {
        id: 'mountain-ranges', type: 'calendar', title: "The year’s mountain ranges",
        narration: 'Before you write anything new, look at what is already fixed: school calendars, trips, launches, the stretches that will eat whole weeks. You are not planning around them yet — you are mapping the terrain, because goals that ignore the terrain die in February.',
        props: { notesKey: 'annualCalendar', landscape: true },
      },
      {
        id: 'someday', type: 'review', title: 'Someday possibilities',
        narration: "This is the someday list — the ideas you parked on purpose. Read it slowly. If the timing has finally turned for one of them, move it into this season. Everything else keeps waiting; that is the point of the list.",
        props: { source: 'someday' },
      },
      {
        id: 'write-goals', type: 'domains-goals', title: "This year’s goals",
        narration: "Now write the goals. Pick three to eight areas of life, and under each one write plain sentences: what you want to be true by this time next year. Do not filter yet — cutting comes later. And keep the ratio honest: two goals you actually want for every one you merely should.",
        byDomain: {
          work: { narration: "Now write the year’s work goals. Under each area work touches — the product, the money, the pipeline, the people — write plain sentences: what you want true by this time next year. Do not filter yet, and keep two goals you actually want for every one you merely should." },
          family: { narration: "Now write the year’s family goals. The kids, each other, the home, the traditions — plain sentences, what you want true by this time next year. Do not filter yet, and keep two goals you actually want for every one you merely should." },
          personal: { narration: "Now write the year’s personal goals. Health, training, headspace, your own fun — plain sentences, what you want true by this time next year. Do not filter yet, and keep two goals you actually want for every one you merely should." },
        },
      },
      {
        id: 'book-next', type: 'book-next', title: 'Anchor the next step',
        narration: "Last step, and it is the one that makes this real: put the seasonal session on the calendar before you close this. If the next session is not booked, this was journaling.",
        props: { bookHorizon: 'seasonal', bookTitle: 'Seasonal planning session' },
      },
    ],
  },

  seasonal: {
    horizon: 'seasonal',
    title: 'Plan the season',
    estMinutes: [25, 35],
    chain: { horizon: 'monthly', label: 'Plan the month now' },
    steps: [
      {
        id: 'welcome', type: 'narration', title: 'A fresh season',
        narration: "This is your seasonal planning session — about half an hour to close out the season that is ending and shape the one ahead. Seasons are the honest unit of life: school terms, summers, the stretch before the holidays. Let’s look at what happened, and then decide what this next one is for.",
      },
      {
        id: 'season-review', type: 'review', title: "Carry, win, or release last season’s picks",
        narration: "Here is everything still open from this season’s list. Celebrate what got done. For each item that didn’t: carry it into the new season if it still matters, park it on Someday if the timing is wrong, or let it go. If you carry something, take one second to notice what stopped it last time.",
        props: { bucket: 'quarter', rows: 'fate' },
      },
      {
        id: 'pick-by-goal', type: 'pick-by-goal', title: 'Choose this season, goal by goal',
        narration: "Now choose the season, goal by goal. Under each of your year goals, add the one or two picks that would actually move it over the next three months. Not everything you could do — the few that matter. A goal with no pick is a goal you are choosing to rest this season, and that is allowed.",
      },
      {
        id: 'standalone-picks', type: 'pick-by-goal', title: "Anything that doesn’t serve a goal",
        narration: "Last, the picks that don’t ladder up to any goal — the season’s must-dos, the household load, the thing you simply want. They belong on the list too. Add anything this season needs that none of your goals covers.",
        props: { standalone: true },
      },
      {
        id: 'season-ahead', type: 'calendar', title: 'The season ahead',
        narration: "Scan the season’s calendar — trips, deadlines, school breaks, the weeks that are already spoken for. Notice how much open space actually exists. Plans that respect the calendar get done; plans that ignore it get abandoned.",
        props: { notesKey: 'tripChildcare' },
      },
      {
        id: 'look-within', type: 'reflect', title: 'Look within',
        narration: 'Before you write anything: how are you, actually? Energy, health, mood. A season planned for the person you wish you were will fall apart in a week. Plan for the person you are right now.',
        props: { notesKey: 'energy', placeholder: 'Energy, health, and mood going into this season…' },
      },
      {
        id: 'book-next', type: 'book-next', title: 'Anchor the next step',
        narration: 'Before you close: book the monthly planning session. Ten seconds now buys you a system that keeps running without willpower.',
        props: { bookHorizon: 'monthly', bookTitle: 'Monthly planning session' },
      },
    ],
  },

  monthly: {
    horizon: 'monthly',
    title: 'Plan the month',
    estMinutes: [15, 25],
    chain: { horizon: 'weekly', label: 'Plan the week now' },
    steps: [
      {
        id: 'welcome', type: 'narration', title: 'A clean slate',
        narration: 'This is your monthly planning session — a clean slate, twelve times a year. One arc, about twenty minutes: celebrate what happened, migrate what is unfinished, scan what is already claimed, check in with yourself, then write the month — its moves, its fun, and the upkeep that keeps life running.',
      },
      {
        id: 'wins', type: 'wins', title: 'Start with the wins',
        narration: 'Start with what actually happened. These are the moves you closed this month — read them slowly and take the credit. Most months hold more than you remember, and the review works better when it starts from evidence instead of guilt.',
      },
      {
        id: 'month-review', type: 'review', title: 'Migrate or release',
        narration: 'Now the honest half. Here is what is still open from the month. For each item, migrate it or release it: carry it forward only if you would write it again today, park it on Someday if the timing is wrong, or let it go. A shorter list you believe is worth more than a long one you ignore.',
        props: { bucket: 'month' },
      },
      {
        id: 'look-at-season', type: 'look-above', title: 'Check the season',
        narration: 'Step up to the season for a moment. These are your picks — notice which ones are moving and which have a month-sized next step waiting. Copy a line down if this is its month; the original stays on the season list.',
        props: { aboveBucket: 'quarter', aboveLabel: 'Your season picks' },
      },
      {
        id: 'month-ahead', type: 'calendar', title: "What’s already claimed",
        narration: 'Before you write anything, scan the month’s calendar and ask one question: what is already claimed? Trips, deadlines, the weeks that are spoken for. The open space that remains is what you are actually planning.',
      },
      {
        id: 'look-within', type: 'reflect', title: 'Look within',
        narration: "A quick check on yourself, and on the people around you. How is your energy? And is there anything with each other or the kids that needs attention this month?",
        props: { notesKey: 'relationships', placeholder: 'Energy — and what needs attention with each other and the kids…' },
        byDomain: {
          work: {
            narration: "A quick check on yourself, and on the people you work with. How is your energy for this? And is there anything with a colleague, a client, or a commitment that needs attention this month?",
            placeholder: 'Energy — and what needs attention with colleagues, clients, commitments…',
          },
          personal: {
            narration: "A quick check on yourself, for yourself. How is your energy, your health, your headspace? And is there a habit or a need of your own that deserves attention this month?",
            placeholder: 'Energy, health, headspace — what of yours needs attention…',
          },
        },
      },
      {
        id: 'projects-in-motion', type: 'projects', title: 'Projects in motion',
        narration: "Your projects in motion, for reference. A month moves a project one concrete chunk at a time — an order placed, a call made, a decision written down. Let these suggest month-sized moves for the list you’re about to write.",
      },
      {
        id: 'write-month', type: 'write-list', title: "Write the month’s list",
        narration: "Write the month’s list. Keep it honest — and build the fun on purpose: one big experience, a few social things, maybe a themed quest. A month with nothing to look forward to is a scheduling failure.",
        props: { bucket: 'month', rows: 'plain', funComposition: true },
      },
      {
        id: 'maintenance', type: 'maintenance', title: 'The upkeep sweep',
        narration: 'Last sweep: the quiet upkeep that keeps the month from ambushing you — the budget, the paperwork, the pile you have been ignoring. Pull this month’s picks onto the list. Small, boring, load-bearing.',
      },
      {
        id: 'book-next', type: 'book-next', title: 'Anchor the next step',
        narration: "Book next month’s session before you close. First weekend of the month works well.",
        props: { bookHorizon: 'monthly', bookTitle: 'Monthly planning session' },
      },
    ],
  },

  weekly: {
    horizon: 'weekly',
    title: 'Plan the week',
    estMinutes: [30, 45],
    chain: { horizon: 'daily', label: 'Plan today now' },
    steps: [
      {
        id: 'welcome', type: 'narration', title: 'The week’s shape',
        narration: 'This is your weekly planning session — the one that keeps the whole system honest. You will clear the inbox, review last week, look at the month and the calendar, and then place the big rocks. Give it half an hour and the week stops happening TO you.',
      },
      {
        id: 'look-around', type: 'inbox', title: 'Look around',
        narration: "First, get current. Here is everything captured into the inbox that hasn’t been dealt with. Give each one a home — a day, a list, Someday — or mark it done. An empty inbox is not tidiness; it is the difference between planning from reality and planning from memory.",
      },
      {
        id: 'week-review', type: 'review', title: "Last week’s list",
        narration: "Here is what is still open from last week. For each item, actively choose its fate: carry it forward, give it a specific day, make it smaller, hand it to someone else, or let it go. No item gets to just linger.",
        props: { bucket: 'week' },
      },
      {
        id: 'look-at-month', type: 'look-above', title: 'Your month list',
        narration: "Your month list, for reference. Which of these does this week need to move? Copy down anything you want on the week’s list — the month list keeps its copy.",
        props: { aboveBucket: 'month', aboveLabel: 'Your month list' },
      },
      {
        id: 'week-ahead', type: 'calendar', title: 'Look ahead',
        narration: "Now audit the week day by day. Look for sneak additions, double bookings, and days with no slack at all. Where are the tight transitions? Which day is secretly already full?",
      },
      {
        id: 'look-within', type: 'reflect', title: 'Look within',
        narration: "Check in with yourself before you commit to anything: sleep debt, physical energy, emotional capacity. Set the week’s expectations to match the human doing it.",
        props: { notesKey: 'energy', placeholder: 'Sleep, energy, capacity going into this week…' },
      },
      {
        id: 'write-week', type: 'write-list', title: "Write the week’s list",
        narration: "Write the week’s task list. Keep it focused — around fifteen items is the honest ceiling for a week that also contains a life. The counter is a nudge, not a wall.",
        props: { bucket: 'week', softCap: 15, rows: 'plain' },
      },
      {
        id: 'place-rocks', type: 'schedule-grid', title: 'Place the big rocks',
        narration: "Now put the most important items on actual days. Drag what matters onto the week — anything with a slot is dramatically more likely to happen than anything floating in a list.",
      },
      {
        id: 'concerns', type: 'reflect', title: 'Concerns & communication',
        narration: 'Last: anything that needs to be talked about, not just done. Logistics to coordinate, decisions pending, worries worth naming. This note is shared — it is the written half of the weekly conversation.',
        props: { notesKey: 'concerns', placeholder: 'To discuss, coordinate, or keep an eye on…' },
        byDomain: {
          work: {
            narration: 'Last: anything that needs to be talked about, not just done. Decisions pending, conversations you are avoiding, things to raise with the people you work with. Naming them here is how they stop circling in your head.',
            placeholder: 'To raise, decide, or keep an eye on at work…',
          },
          personal: {
            narration: 'Last: anything worth naming, just for you. Worries circling, decisions pending, things you keep putting off. Written down, they take up less room in your head.',
            placeholder: 'Worries, decisions, things to keep an eye on…',
          },
        },
      },
    ],
  },

  daily: {
    horizon: 'daily',
    title: 'Plan today',
    estMinutes: [5, 10],
    steps: [
      {
        id: 'look-back', type: 'review', title: 'Look back',
        narration: "A quick look at what carried over. Nothing here is a failure — it is just yesterday’s honest remainder. Give each item a new home in one tap.",
        props: { source: 'overdue' },
      },
      {
        id: 'look-ahead', type: 'calendar', title: 'Look ahead',
        narration: "Here is today’s shape — the hard commitments and, more importantly, the gaps between them. The gaps are the day’s actual capacity.",
      },
      {
        id: 'look-within', type: 'reflect', title: 'Look within',
        narration: "One word for today — how you want it to feel, or how you are. Then size the plan to match: on a packed or foggy day, one real task is a victory.",
        props: { notesKey: 'oneWord', placeholder: 'One word for today…' },
      },
      {
        id: 'pick-today', type: 'look-above', title: 'Pick from the week',
        narration: "Here is your week list. Tap the items today should carry — they move onto today. Match the count to the open space you just saw, not to your ambition.",
        props: { aboveBucket: 'week', aboveLabel: 'Your week list', pick: true },
      },
    ],
  },
}
