import {useState,useRef,useEffect} from 'react'
import {createRoot} from 'react-dom/client'
import {ArrowRight,Plus,Check,X} from 'lucide-react'
import {initial,add,descendants,type Node} from './model'
import './style.css'
const periods=['Year','Season','Month','Week','Today']
const nouns=['yearly intention','seasonal milestone','monthly plan','weekly action','daily action']
const questions=['What would you like this year to be about?','What would progress look like this season?','What do you want in place this month?','What will you actually do this week?','What fits today?']
type Edit={id?:string;parent:string|null;level:number;color:string}
function App(){
 const [mode,setMode]=useState('Constellation'),[stage,setStage]=useState(0),[nodes,setNodes]=useState(initial),[editing,setEditing]=useState<Edit|null>(null),[text,setText]=useState(''),[notice,setNotice]=useState(''),[reveal,setReveal]=useState(false)
 const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(editing)dialog.current?.showModal();else dialog.current?.close()},[editing])
 const edit=(node:Node)=>{setEditing({...node});setText(node.text)}
 const beginAdd=(parent:Node|null,level:number)=>{setEditing({parent:parent?.id||null,level,color:parent?.color||'#9981a2'});setText('')}
 const commit=()=>{if(!editing||!text.trim())return;setNodes(old=>editing.id?old.map(n=>n.id===editing.id?{...n,text:text.trim()}:n):add(old,{...editing,id:crypto.randomUUID(),text}));setNotice(editing.id?'Updated this item. Its branches stay connected.':'Added another item under this parent. Other branches are unchanged.');setEditing(null)}
 const tree=(parent:Node):React.ReactNode=><ul className="branch-tree">{nodes.filter(n=>n.parent===parent.id).map(n=><li key={n.id}><small>{periods[n.level]}</small><button onClick={()=>edit(n)}>{n.text} ↗</button>{tree(n)}</li>)}</ul>
 const roots=nodes.filter(n=>n.parent===null&&n.level<=stage)
 return <div className="shape-study"><div className="study-note">BRANCHING PLAN STUDY · FICTIONAL DATA · RESETS ON RELOAD <a href="../today-study/index.html">Today baseline ↗</a></div><header><span className="brand">✳ SYMPHONY</span><span className="edition">A plan taking shape</span><span className="draft">● Sample draft</span></header><nav className="treatments" aria-label="Visual treatment">{['Constellation','Landscape','Woven threads'].map(m=><button key={m} aria-pressed={m===mode} onClick={()=>setMode(m)}>{m}</button>)}</nav><div className="heading"><div><p className="eyebrow">{stage===0?'GATHER ALL YOUR INTENTIONS':`${periods[stage-1].toUpperCase()} → ${periods[stage].toUpperCase()}`}</p><h1>{questions[stage]}</h1></div><button className="quiet" onClick={()=>setReveal(v=>!v)} aria-pressed={reveal}>{reveal?'Show this horizon':'See all branches'}</button></div><nav className="horizons" aria-label="Planning horizon">{periods.map((p,i)=><button key={p} aria-current={i===stage?'step':undefined} onClick={()=>{setStage(i);setNotice('')}}><span>{i+1}</span>{p}</button>)}<small>All intentions together · multiple items welcome</small></nav><main className={`field branching ${mode==='Woven threads'?'woven':mode.toLowerCase()}`} aria-label={`${mode} branching plan`}>
 {roots.map((root,index)=>{const related=descendants(nodes,root.id);const parents=stage===root.level?[root]:[root,...related].filter(n=>n.level===stage-1);return <section className="intention branch-root" key={root.id} style={{'--tone':root.color,'--order':index} as React.CSSProperties}><div className="branch-identity"><div className="glyph" aria-hidden="true"><span/><i/>{Array.from({length:stage+1},(_,n)=><em key={n} style={{'--n':n} as React.CSSProperties}/>)}</div><div><p className="eyebrow">{periods[root.level]} · {String(index+1).padStart(2,'0')}</p><button className="plan-wording" onClick={()=>edit(root)}>{root.text} ↗</button></div></div>{reveal?tree(root):stage>root.level?<div className="parent-groups">{parents.map(parent=><section className="parent-group" key={parent.id}><p className="parent-label">{periods[parent.level]} · {parent.text}</p><div className="child-items">{nodes.filter(n=>n.parent===parent.id&&n.level===stage).map(child=><button key={child.id} className="child-node" onClick={()=>edit(child)}><span className="node-dot"/>{child.text}<span className="edit-mark">↗</span></button>)}</div><button className="add-child" onClick={()=>beginAdd(parent,stage)}><Plus size={14}/> Add another {nouns[stage]}<span className="sr-only"> under {parent.text}</span></button></section>)}{!parents.length&&<div className="missing-branch"><p>No {periods[stage-1].toLowerCase()} items here yet. Nothing has been invented for you.</p><button onClick={()=>setStage(stage-1)}>Return to {periods[stage-1]} <ArrowRight size={14}/></button></div>}</div>:<p className="root-note">{root.level===0?'An intention for the year. Gather the others before shaping the season.':'An independent item. It can have its own next steps.'}</p>}</section>})}
 <button className="add-intention" onClick={()=>beginAdd(null,stage)}><Plus size={20}/>{stage===0?'Add another yearly intention':`Add an independent ${nouns[stage]}`}</button></main><div className="checkpoint"><div><span className="eyebrow">{stage+1} OF 5 · {periods[stage].toUpperCase()}</span><p>{stage===0?'Have you gathered what matters across your year?':'Review all the branches before moving to the next horizon.'}</p></div>{stage<4?<button className="next" onClick={()=>setStage(s=>s+1)}>Continue to {periods[stage+1]} <ArrowRight size={17}/></button>:<a className="next" href="../today-study/index.html">Explore Today separately <ArrowRight size={17}/></a>}</div><p className="notice" role="status">{notice||'Each item can have several children. Click to edit; use Add another beside the relevant parent.'}</p><footer>All changes stay in this tab and reset on reload. Today is a separate sample; this plan does not transfer there. No live voice or account writes.</footer><dialog ref={dialog} onClose={()=>setEditing(null)} aria-label="Shape your plan" className="editor"><form onSubmit={e=>{e.preventDefault();commit()}}><div><span className="eyebrow">{periods[editing?.level||0]} · YOUR WORDS</span><button type="button" aria-label="Cancel" onClick={()=>setEditing(null)}><X size={18}/></button></div><h2>{editing?.id?'Shape this item.':'Add another possibility.'}</h2>{editing?.parent&&<p>Connected to: <strong>{nodes.find(n=>n.id===editing.parent)?.text}</strong></p>}<textarea aria-label="Plan wording" maxLength={160} value={text} onChange={e=>setText(e.target.value)}/><p>Your other items and connections remain unchanged.</p><button className="next" disabled={!text.trim()}><Check size={17}/> Keep in sample draft</button></form></dialog></div>
}
createRoot(document.getElementById('root')!).render(<App/> )
