import {useState} from 'react'
import {Plus,ArrowLeft} from 'lucide-react'
import {terms,type Node} from './model'
type Props={nodes:Node[];edit:(n:Node)=>void;add:(n:Node,level:number)=>void}
export function Spatial({nodes,edit,add}:Props){
 const [focusId,setFocus]=useState('weekends')
 const focus=nodes.find(n=>n.id===focusId)||nodes[0]
 const kids=nodes.filter(n=>n.parent===focus.id)
 const parents:Node[]=[];let ancestor=nodes.find(n=>n.id===focus.parent);while(ancestor){parents.unshift(ancestor);ancestor=nodes.find(n=>n.id===ancestor?.parent)}
 const label=(n:Node)=><div className="spatial-label"><small>{terms[n.level]}</small><button onClick={()=>edit(n)}>{n.text} ↗</button>{n.level>=3&&<span>{n.date?`Scheduled · ${n.date}`:'Not scheduled to a day'}</span>}</div>
 return <section className="orbital-focus" style={{'--tone':focus.color} as React.CSSProperties}><div className="orbit-breadcrumb">{parents.map(n=><button key={n.id} onClick={()=>setFocus(n.id)}>{terms[n.level]} · {n.text} /</button>)}</div><div className="focus-picker"><label>Focus <select value={focus.id} onChange={e=>setFocus(e.target.value)}>{nodes.filter(n=>n.level<4).map(n=><option key={n.id} value={n.id}>{terms[n.level]} · {n.text}</option>)}</select></label>{focus.parent&&<button onClick={()=>setFocus(focus.parent!)}><ArrowLeft size={14}/> Broader view</button>}</div><div className="orbital-stage"><svg className="orbit-line" viewBox="0 0 900 540" preserveAspectRatio="none" aria-hidden="true"><ellipse cx="450" cy="270" rx="280" ry="165"/>{kids.slice(0,4).map((n,i)=><path key={n.id} d={`M450 270 L${i%2?730:170} ${i<2?105:435}`}/>)}</svg><div className="orbit-center">{label(focus)}{focus.level<4&&<button className="spatial-add" onClick={()=>add(focus,focus.level+1)}><Plus size={14}/> {focus.level===3?'Add optional task step':`Add ${terms[focus.level+1].toLowerCase()}`}</button>}</div>{kids.slice(0,4).map((n,i)=><div className={`satellite satellite-${i}`} key={n.id}><span className="planet"/>{label(n)}{n.level<4&&<button className="focus-child" onClick={()=>setFocus(n.id)}>Explore this branch →</button>}</div>)}{!kids.length&&<p className="orbit-empty">Room for the next part of your plan. Add one when you’re ready.</p>}</div>{kids.length>4&&<div className="orbit-overflow"><p>More in this orbit</p>{kids.slice(4).map(n=><div className="satellite" key={n.id}>{label(n)}{n.level<4&&<button className="focus-child" onClick={()=>setFocus(n.id)}>Explore this branch →</button>}</div>)}</div>}<p className="spatial-help">The center is the parent; each satellite is one of its children. Labels stay readable. Nothing moves unless you choose a different focus.</p></section>
}
